apiVersion: v1
kind: Service
metadata:
  name: sso-service
  labels:
    app: sso
spec:
  ports:
  - name: sso-service
    port: 8083
    nodePort: 30004
  type: NodePort
  selector:
    app: sso-service