apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: sso
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DATA_BASE: a2V5Y2xvYWs=
  USER: ZnVyaWFsZm9uc28=
  PASS: QWRtaW4xMjM=
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==