apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 3s
      evaluation_interval: 3s

    scrape_configs:
      - job_name: prometheus-service
        static_configs:
          - targets: ['prometheus-service:9090']

      - job_name: cadvisor-service
        static_configs:
          - targets: ['cadvisor-service:8080']

      - job_name: sso-service
        static_configs:
          - targets: ['sso-service:8083']
