apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
  type: LoadBalancer
  selector:
    app: prometheus
