apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    app: grafana
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/grafana
