apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: keycloakpot
        envFrom:
          - secretRef:
              name: keycloak-secret
          - configMapRef:
              name: keycloak-configmap