apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: sso
type: Opaque
data:
  KEYCLOAK_ADMIN_USER: ZnVyaWFsZm9uc28=
  KEYCLOAK_ADMIN_PASSWORD: QWRtaW4xMjM=
  KEYCLOAK_DATABASE_USER: ZnVyaWFsZm9uc28=
  KEYCLOAK_DATABASE_PASSWORD: QWRtaW4xMjM=