apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: sso
spec:
  ports:
  - name: keycloak
    port: 8080
    nodePort: 30001
  type: LoadBalancer
  selector:
    app: keycloak