apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  ports:
  - name: demo-service
    port: 8082
    nodePort: 30003
  type: NodePort
  selector:
    app: demo-service