apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor-service
  labels:
    app: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /var/run
              name: var-run
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /var/lib/docker
              name: var-lib-docker
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: var-run
          hostPath:
            path: /var/run
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker
            type: Directory
