apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-front-deployment
  labels:
    app: user-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-front
  template:
    metadata:
      labels:
        app: user-front
    spec:
      containers:
      - name: user-front
        image: furialfonso/user-front:test
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-src
          mountPath: /app/src
        - name: user-front-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: app-src
        hostPath:
          path: /path/to/your/src
      - name: user-front-config
        configMap:
          name: user-front-config